import { Prisma } from "@prisma/client";

export interface NormalizedErrorResponse {
  statusCode: number;
  message: string;
  errorCode: string;
  details?: unknown;
}

/**
 * Type guard to check if an unknown error is generated by Prisma
 */
export function isPrismaError(error: unknown): boolean {
  return (
    error instanceof Prisma.PrismaClientKnownRequestError ||
    error instanceof Prisma.PrismaClientUnknownRequestError ||
    error instanceof Prisma.PrismaClientRustPanicError ||
    error instanceof Prisma.PrismaClientInitializationError ||
    error instanceof Prisma.PrismaClientValidationError
  );
}

/**
 * Normalizes Prisma errors into safe, client-friendly HTTP status codes,
 * standardized error codes, and clean human-readable messages.
 * Prevents leaking raw SQL schema details, internal paths, or engine stack traces.
 */
export function normalizePrismaError(
  error: unknown,
): NormalizedErrorResponse | null {
  // 1. Known Prisma Request Errors (P1xxx connection & P2xxx constraint errors)
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      // --- Connection & Network Issues (P1xxx) ---
      case "P1000":
        return {
          statusCode: 500,
          errorCode: "DATABASE_AUTH_FAILED",
          message:
            "Database authentication failed. Please verify server credentials.",
        };

      case "P1001":
        return {
          statusCode: 503,
          errorCode: "DATABASE_UNAVAILABLE",
          message:
            "Database server is unreachable. Please verify database connectivity.",
        };

      case "P1002":
      case "P1008":
        return {
          statusCode: 504,
          errorCode: "DATABASE_TIMEOUT",
          message: "Database query timed out. Please try again.",
        };

      case "P1003":
        return {
          statusCode: 500,
          errorCode: "DATABASE_NOT_FOUND",
          message: "Configured database does not exist on the database host.",
        };

      case "P1017":
        return {
          statusCode: 503,
          errorCode: "DATABASE_CONNECTION_CLOSED",
          message: "Database connection was closed unexpectedly by the server.",
        };

      // --- Query & Data Constraint Issues (P2xxx) ---
      case "P2000": {
        const column = (error.meta?.column_name as string) || "field";
        return {
          statusCode: 400,
          errorCode: "VALUE_TOO_LONG",
          message: `The provided value for '${column}' exceeds the maximum allowed length.`,
        };
      }

      case "P2002": {
        const target = Array.isArray(error.meta?.target)
          ? error.meta.target.join(", ")
          : (error.meta?.target as string) || "field";
        return {
          statusCode: 409,
          errorCode: "DUPLICATE_RECORD",
          message: `A record with this ${target} already exists.`,
        };
      }

      case "P2003": {
        const field = (error.meta?.field_name as string) || "referenced record";
        return {
          statusCode: 400,
          errorCode: "FOREIGN_KEY_VIOLATION",
          message: `Foreign key constraint failed: '${field}' does not exist or cannot be referenced.`,
        };
      }

      case "P2014":
        return {
          statusCode: 400,
          errorCode: "RELATION_VIOLATION",
          message:
            "The requested operation violates a required database relationship.",
        };

      case "P2025":
        return {
          statusCode: 404,
          errorCode: "RECORD_NOT_FOUND",
          message:
            (error.meta?.cause as string) ||
            "The requested record was not found.",
        };

      default:
        return {
          statusCode: 400,
          errorCode: error.code || "DATABASE_REQUEST_ERROR",
          message: "A database constraint or query operation error occurred.",
        };
    }
  }

  // 2. Query Validation Error (invalid argument types or missing required fields)
  if (error instanceof Prisma.PrismaClientValidationError) {
    return {
      statusCode: 400,
      errorCode: "DATABASE_VALIDATION_ERROR",
      message:
        "Invalid data format or missing required fields for database operation.",
    };
  }

  // 3. Database Initialization / Connection String Error
  if (error instanceof Prisma.PrismaClientInitializationError) {
    return {
      statusCode: 503,
      errorCode: "DATABASE_INITIALIZATION_ERROR",
      message:
        "Could not connect to the database engine. Please check service availability.",
    };
  }

  // 4. Critical Engine Rust Panic
  if (error instanceof Prisma.PrismaClientRustPanicError) {
    return {
      statusCode: 500,
      errorCode: "DATABASE_ENGINE_PANIC",
      message: "A critical database engine panic occurred.",
    };
  }

  // 5. Unknown Request Error
  if (error instanceof Prisma.PrismaClientUnknownRequestError) {
    return {
      statusCode: 500,
      errorCode: "DATABASE_UNKNOWN_ERROR",
      message: "An unexpected database error occurred.",
    };
  }

  return null;
}

export default normalizePrismaError;
